### ISSUE TITLE
Install Problems Ubuntu 14.04 with cuDNN and CUDA 7.5, Anaconda2, PyCharm IDE, numpy 1.10

### ISSUE THREAD

**Issue by filmo** [andersbll/cudarray#35]
Ultimately I'm getting following error:

```
Traceback (most recent call last):
  File "/home/philglau/PycharmProjects/testing/cudarry_test.py", line 7, in <module>
    import cudarray as ca
  File "/home/philglau/anaconda2/lib/python2.7/site-packages/cudarray-0.1.dev0-py2.7-linux-x86_64.egg/cudarray/__init__.py", line 20, in <module>
    from .cudarray import *
  File "/home/philglau/anaconda2/lib/python2.7/site-packages/cudarray-0.1.dev0-py2.7-linux-x86_64.egg/cudarray/cudarray.py", line 2, in <module>
    from .wrap.array_data import ArrayData
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory
```

I have CUDA and cuDNN installed and working in ``/usr/local/cuda`` and prior to ``make``  the following environmental variables were set as:

```
philglau@gpu-workstation:~$ echo $INSTALL_PREFIX
/home/philglau/anaconda2
philglau@gpu-workstation:~$ echo $CUDA_PREFIX
/usr/local/cuda-7.5
philglau@gpu-workstation:~$ echo $CUDNN_ENABLED
1
philglau@gpu-workstation:~$ 
```

inside of ``/usr/local/cuda-7.5`` I can see the libcudart.so.7.5
```
philglau@gpu-workstation:/usr/local/cuda-7.5/lib64$ ll *libcudart.so*
lrwxrwxrwx 1 root root     16 Aug 15 08:55 libcudart.so -> libcudart.so.7.5*
lrwxrwxrwx 1 root root     19 Aug 15 08:55 libcudart.so.7.5 -> libcudart.so.7.5.18*
-rwxr-xr-x 1 root root 383336 Aug 15 08:55 libcudart.so.7.5.18*
philglau@gpu-workstation:/usr/local/cuda-7.5/lib64$ 
```
I tried ``make`` with CUDA prefix set to both ``/usr/local/cuda`` and ``/usr/local/cuda-7.5`` but that didn't make a difference. (I didn't think it would)

Any thoughts on what I should try to do to resolve this error? Thank you in advance for your help.

**Comment by filmo** [comment]
I seemed to have resolved this by creating a symbolic link from the library on the CUDA path to the anaconda library path. Perhaps something isn't right in the makefile as I set my environment variables correctly, but after compile cudarray looked in the /path/to/anaconda/lib for the cuda libraries rather than in /path/to/cuda_install

For anybody who runs into this, I fixed it by:

```
cd /path/to/anaconda/lib
ln -s /usr/local/cuda/lib64/libcudart.so.7.5 libcudart.so.7.5
```

Kind of a 'hackish' fixes, so your mileage may vary.

**Comment by filmo** [comment]
I spoke too soon. Inside of PyCharm I'm now getting an error about 'the next' library in the chain being missing. Now libcublas.so.7.5 is 'not found'. I can probably symbolically link this as well, but it seems like this needs to be fixed at a higher level 

Interestingly, if I enter the Anaconda interpreter from the command line, cudarray works as near as I can tell. Just not from inside PyCharm. (Which seems weird.)

**Comment by asanakoy** [comment]
Just alter the run script for PyCharm (see [this post](http://stackoverflow.com/questions/19715724/pycharm-environment-different-than-command-line/34315644#34315644)) and run PyCharm from desktop as usual. If error still appears - in PyCharm console run `sudo ldconfig /usr/local/cuda-7.5/lib64`

**Comment by AndersonJo** [comment]
Thanks filmo. 
After I added the CUDA environment variables it runs well in Pycharm.
